version: '3.1'

services:

  cars-db:
    image: car-service-cars-db:0.0.1
    ports:
    - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: car
      MONGO_INITDB_ROOT_PASSWORD: car
      MONGO_INITDB_DATABASE: cars

  cars-app:
    image: car-service-cars:0.0.1-SNAPSHOT
    ports:
    - 9091:8080
    restart: always

  ui:
    image: car-service-ui:0.0.1-SNAPSHOT
    ports:
    - 9090:8080
    restart: always
    environment:
      CAR_SERVICE_HOST: 192.168.99.100
      CAR_SERVICE_CARS_PORT: 9091
