version: '3.1'

services:

  cars-db:
    image: car-service-cars-db:0.0.1
    ports:
    - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: car
      MONGO_INITDB_ROOT_PASSWORD: car
      MONGO_INITDB_DATABASE: customercars

  cars-app:
    image: car-service-cars-app:0.0.1
    ports:
    - 8071:8080
    restart: always

  ui:
    image: car-service-ui-app:0.0.1
    ports:
    - 8080:8080
    restart: always
